#############################################################################
# Makefile for building: VSPSetup
# Generated by qmake (3.1) (Qt 6.9.1)
# Project:  ../VSPSetup.pro
# Template: lib
# Command: $(HOME)/Qt/6.9.1/macos/bin/qmake -o VSPSetup.xcodeproj/project.pbxproj ../VSPSetup.pro -spec macx-xcode
#############################################################################

MAKEFILE      = project.pbxproj

EQ            = =

QMAKE    = $(HOME)/Qt/6.9.1/macos/bin/qmake
VSPSetup.framework/Versions/A/Resources/VSPSetup.prl:
	@$(QMAKE) -prl $(PWD)/../VSPSetup.pro  -spec macx-xcode
VSPSetup.xcodeproj/project.pbxproj: $(PWD)/../VSPSetup.pro $(HOME)/Qt/6.9.1/macos/mkspecs/features/spec_pre.prf \
		$(HOME)/Qt/6.9.1/macos/mkspecs/features/device_config.prf \
		$(HOME)/Qt/6.9.1/macos/mkspecs/common/unix.conf \
		$(HOME)/Qt/6.9.1/macos/mkspecs/common/mac.conf \
		$(HOME)/Qt/6.9.1/macos/mkspecs/common/macx.conf \
		$(HOME)/Qt/6.9.1/macos/mkspecs/common/sanitize.conf \
		$(HOME)/Qt/6.9.1/macos/mkspecs/common/gcc-base.conf \
		$(HOME)/Qt/6.9.1/macos/mkspecs/common/gcc-base-mac.conf \
		$(HOME)/Qt/6.9.1/macos/mkspecs/common/clang.conf \
		$(HOME)/Qt/6.9.1/macos/mkspecs/common/clang-mac.conf \
		$(HOME)/Qt/6.9.1/macos/mkspecs/qconfig.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_ext_freetype.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_ext_libpng.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_ext_openxr_loader.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3danimation.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3danimation_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dcore.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dcore_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dextras.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dextras_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dinput.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dinput_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dlogic.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dlogic_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dquick.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dquick_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dquickanimation.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dquickextras.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dquickinput.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dquicklogic.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dquicklogic_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dquickrender.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dquickscene3d.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dquickscene3d_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3drender.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3drender_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_bluetooth.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_bluetooth_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_bodymovin_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_charts.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_charts_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_chartsqml.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_chartsqml_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_concurrent.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_connectivity_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_core.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_core5compat.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_core5compat_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_core_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_datavisualization.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_datavisualization_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_datavisualizationqml.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_datavisualizationqml_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_dbus.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_designer.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_designer_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_example_icons_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_ffmpegmediapluginimpl_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_graphs.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_graphs_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_graphswidgets.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_graphswidgets_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_grpc.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_grpc_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_grpcquick.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_grpcquick_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_gui.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_gui_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_help.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_help_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_httpserver.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_httpserver_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_insighttracker.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_insighttracker_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_insighttrackerqml.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_insighttrackerqml_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_jsonrpc_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_labsplatform.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_labsplatform_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_labssettings.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_languageserver_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_linguist.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_location.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_location_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_multimedia.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_multimedia_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_multimediatestlibprivate_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_multimediawidgets.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_network.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_network_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_networkauth.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_networkauth_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_nfc.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_nfc_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_opengl.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_pdf.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_pdf_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_pdfquick.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_pdfquick_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_pdfwidgets.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_png_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_positioning.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_positioning_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_positioningquick.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_positioningquick_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_printsupport.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_protobuf.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_protobuf_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_protobufqtcoretypes.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_protobufqtcoretypes_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_protobufqtguitypes.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_protobufqtguitypes_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_protobufquick.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_protobufquick_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_protobufwellknowntypes.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_protobufwellknowntypes_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qml.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qml_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlassetdownloader.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlassetdownloader_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlcompiler.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlformat_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlls_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlmeta.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlmeta_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlnetwork.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmltest.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3d.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3d_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3deffects.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dparticles.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dphysics.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dphysics_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dutils.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dxr.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dxr_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickeffects.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickeffects_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quicktimeline.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickvectorimage.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickvectorimage_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_remoteobjects.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_repparser.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_repparser_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_scxml.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_scxml_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_scxmlglobal_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_scxmlqml.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_sensors.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_sensors_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_sensorsquick.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_serialbus.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_serialbus_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_serialport.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_serialport_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_shadertools.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_shadertools_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_spatialaudio.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_sql.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_sql_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_statemachine.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_statemachine_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_statemachineqml.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_svg.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_svg_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_testinternals_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_testlib.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_texttospeech.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_texttospeech_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_tools_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_uitools.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_virtualkeyboardqml.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_virtualkeyboardqml_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_virtualkeyboardsettings.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_virtualkeyboardsettings_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_webchannel.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_webchannel_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_webchannelquick.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_webchannelquick_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_webenginecore.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_webenginecore_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_webenginequick.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_webenginequick_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_webenginewidgets.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_websockets.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_websockets_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_webview.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_webview_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_webviewquick.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_webviewquick_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_widgets.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_xml.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_xml_private.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		$(HOME)/Qt/6.9.1/macos/mkspecs/features/qt_functions.prf \
		$(HOME)/Qt/6.9.1/macos/mkspecs/features/qt_config.prf \
		$(HOME)/Qt/6.9.1/macos/mkspecs/macx-clang/qmake.conf \
		$(HOME)/Qt/6.9.1/macos/mkspecs/macx-xcode/qmake.conf \
		$(HOME)/Qt/6.9.1/macos/mkspecs/features/spec_post.prf \
		.qmake.stash \
		$(HOME)/Qt/6.9.1/macos/mkspecs/features/exclusive_builds.prf \
		$(HOME)/Qt/6.9.1/macos/mkspecs/features/mac/sdk.prf \
		$(HOME)/Qt/6.9.1/macos/mkspecs/features/toolchain.prf \
		$(HOME)/Qt/6.9.1/macos/mkspecs/features/mac/toolchain.prf \
		$(HOME)/Qt/6.9.1/macos/mkspecs/features/default_pre.prf \
		$(HOME)/Qt/6.9.1/macos/mkspecs/features/mac/default_pre.prf \
		$(HOME)/Qt/6.9.1/macos/mkspecs/features/resolve_config.prf \
		$(HOME)/Qt/6.9.1/macos/mkspecs/features/default_post.prf \
		$(HOME)/Qt/6.9.1/macos/mkspecs/features/mac/default_post.prf \
		$(HOME)/Qt/6.9.1/macos/mkspecs/features/mac/objective_c.prf \
		$(HOME)/Qt/6.9.1/macos/mkspecs/features/lrelease.prf \
		$(HOME)/Qt/6.9.1/macos/mkspecs/features/mac/mac.prf \
		$(HOME)/Qt/6.9.1/macos/mkspecs/features/warn_on.prf \
		$(HOME)/Qt/6.9.1/macos/mkspecs/features/qmake_use.prf \
		$(HOME)/Qt/6.9.1/macos/mkspecs/features/file_copies.prf \
		$(HOME)/Qt/6.9.1/macos/mkspecs/features/mac/rez.prf \
		$(HOME)/Qt/6.9.1/macos/mkspecs/features/mac/asset_catalogs.prf \
		$(HOME)/Qt/6.9.1/macos/mkspecs/features/testcase_targets.prf \
		$(HOME)/Qt/6.9.1/macos/mkspecs/features/exceptions.prf \
		$(HOME)/Qt/6.9.1/macos/mkspecs/features/yacc.prf \
		$(HOME)/Qt/6.9.1/macos/mkspecs/features/lex.prf \
		../VSPSetup.pro
	$(QMAKE) -o VSPSetup.xcodeproj/project.pbxproj ../VSPSetup.pro -spec macx-xcode
	@echo 'warning: Xcode project has been regenerated, custom settings have been lost. Use CONFIG+=no_autoqmake to prevent this behavior in the future, at the cost of requiring manual project change tracking.'
$(HOME)/Qt/6.9.1/macos/mkspecs/features/spec_pre.prf:
$(HOME)/Qt/6.9.1/macos/mkspecs/features/device_config.prf:
$(HOME)/Qt/6.9.1/macos/mkspecs/common/unix.conf:
$(HOME)/Qt/6.9.1/macos/mkspecs/common/mac.conf:
$(HOME)/Qt/6.9.1/macos/mkspecs/common/macx.conf:
$(HOME)/Qt/6.9.1/macos/mkspecs/common/sanitize.conf:
$(HOME)/Qt/6.9.1/macos/mkspecs/common/gcc-base.conf:
$(HOME)/Qt/6.9.1/macos/mkspecs/common/gcc-base-mac.conf:
$(HOME)/Qt/6.9.1/macos/mkspecs/common/clang.conf:
$(HOME)/Qt/6.9.1/macos/mkspecs/common/clang-mac.conf:
$(HOME)/Qt/6.9.1/macos/mkspecs/qconfig.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_ext_freetype.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_ext_libjpeg.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_ext_libpng.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_ext_openxr_loader.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3danimation.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3danimation_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dcore.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dcore_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dextras.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dextras_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dinput.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dinput_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dlogic.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dlogic_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dquick.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dquick_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dquickanimation.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dquickextras.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dquickextras_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dquickinput.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dquickinput_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dquicklogic.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dquicklogic_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dquickrender.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dquickrender_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dquickscene2d.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dquickscene3d.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3dquickscene3d_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3drender.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_3drender_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_bluetooth.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_bluetooth_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_bodymovin_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_charts.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_charts_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_chartsqml.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_chartsqml_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_concurrent.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_concurrent_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_connectivity_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_core.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_core5compat.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_core5compat_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_core_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_datavisualization.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_datavisualization_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_datavisualizationqml.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_datavisualizationqml_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_dbus.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_dbus_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_designer.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_designer_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_designercomponents_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_example_icons_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_fb_support_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_ffmpegmediapluginimpl_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_freetype_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_graphs.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_graphs_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_graphswidgets.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_graphswidgets_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_grpc.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_grpc_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_grpcquick.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_grpcquick_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_gui.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_gui_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_help.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_help_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_httpserver.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_httpserver_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_insighttracker.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_insighttracker_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_insighttrackerqml.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_insighttrackerqml_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_jpeg_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_jsonrpc_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_labsanimation.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_labsanimation_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_labsplatform.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_labsplatform_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_labssettings.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_labssettings_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_labssharedimage.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_languageserver_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_linguist.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_location.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_location_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_multimedia.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_multimedia_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_multimediaquick_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_multimediatestlibprivate_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_multimediawidgets.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_network.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_network_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_networkauth.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_networkauth_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_nfc.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_nfc_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_opengl.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_opengl_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_openglwidgets.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_pdf.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_pdf_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_pdfquick.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_pdfquick_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_pdfwidgets.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_png_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_positioning.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_positioning_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_positioningquick.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_positioningquick_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_printsupport.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_printsupport_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_protobuf.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_protobuf_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_protobufqtcoretypes.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_protobufqtcoretypes_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_protobufqtguitypes.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_protobufqtguitypes_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_protobufquick.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_protobufquick_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_protobufwellknowntypes.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_protobufwellknowntypes_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qdoccatch_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qml.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qml_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlassetdownloader.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlassetdownloader_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlcompiler.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlcore.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlcore_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmldebug_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmldom_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlformat_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlintegration.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlls_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlmeta.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlmeta_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlmodels.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlnetwork.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlnetwork_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmltest.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmltest_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3d.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3d_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dassetimport.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dassetutils.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dassetutils_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3deffects.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3deffects_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dglslparser_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dhelpers.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dhelpers_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3diblbaker.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dparticleeffects.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dparticles.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dphysics.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dphysics_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3druntimerender.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dutils.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dutils_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dxr.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick3dxr_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quick_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2basic.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2fusion.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2imagine.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2iosstyleimpl_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2macosstyleimpl_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2material.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2material_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2universal.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickdialogs2.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickeffects.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickeffects_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quicklayouts.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickparticles_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickshapes_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quicktemplates2.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quicktimeline.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quicktimeline_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickvectorimage.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickvectorimage_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickwidgets.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_remoteobjects.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_remoteobjects_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_remoteobjectsqml.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_repparser.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_repparser_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_scxml.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_scxml_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_scxmlglobal_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_scxmlqml.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_scxmlqml_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_sensors.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_sensors_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_sensorsquick.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_sensorsquick_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_serialbus.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_serialbus_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_serialport.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_serialport_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_shadertools.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_shadertools_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_spatialaudio.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_spatialaudio_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_sql.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_sql_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_statemachine.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_statemachine_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_statemachineqml.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_statemachineqml_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_svg.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_svg_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_svgwidgets.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_testinternals_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_testlib.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_testlib_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_texttospeech.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_texttospeech_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_tools_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_uiplugin.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_uitools.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_uitools_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_virtualkeyboard.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_virtualkeyboardqml.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_virtualkeyboardqml_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_virtualkeyboardsettings.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_virtualkeyboardsettings_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_webchannel.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_webchannel_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_webchannelquick.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_webchannelquick_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_webenginecore.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_webenginecore_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_webenginequick.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_webenginequick_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_webenginewidgets.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_websockets.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_websockets_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_webview.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_webview_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_webviewquick.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_webviewquick_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_widgets.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_widgets_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_xml.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_lib_xml_private.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri:
$(HOME)/Qt/6.9.1/macos/mkspecs/features/qt_functions.prf:
$(HOME)/Qt/6.9.1/macos/mkspecs/features/qt_config.prf:
$(HOME)/Qt/6.9.1/macos/mkspecs/macx-clang/qmake.conf:
$(HOME)/Qt/6.9.1/macos/mkspecs/macx-xcode/qmake.conf:
$(HOME)/Qt/6.9.1/macos/mkspecs/features/spec_post.prf:
.qmake.stash:
$(HOME)/Qt/6.9.1/macos/mkspecs/features/exclusive_builds.prf:
$(HOME)/Qt/6.9.1/macos/mkspecs/features/mac/sdk.prf:
$(HOME)/Qt/6.9.1/macos/mkspecs/features/toolchain.prf:
$(HOME)/Qt/6.9.1/macos/mkspecs/features/mac/toolchain.prf:
$(HOME)/Qt/6.9.1/macos/mkspecs/features/default_pre.prf:
$(HOME)/Qt/6.9.1/macos/mkspecs/features/mac/default_pre.prf:
$(HOME)/Qt/6.9.1/macos/mkspecs/features/resolve_config.prf:
$(HOME)/Qt/6.9.1/macos/mkspecs/features/default_post.prf:
$(HOME)/Qt/6.9.1/macos/mkspecs/features/mac/default_post.prf:
$(HOME)/Qt/6.9.1/macos/mkspecs/features/mac/objective_c.prf:
$(HOME)/Qt/6.9.1/macos/mkspecs/features/lrelease.prf:
$(HOME)/Qt/6.9.1/macos/mkspecs/features/mac/mac.prf:
$(HOME)/Qt/6.9.1/macos/mkspecs/features/warn_on.prf:
$(HOME)/Qt/6.9.1/macos/mkspecs/features/qmake_use.prf:
$(HOME)/Qt/6.9.1/macos/mkspecs/features/file_copies.prf:
$(HOME)/Qt/6.9.1/macos/mkspecs/features/mac/rez.prf:
$(HOME)/Qt/6.9.1/macos/mkspecs/features/mac/asset_catalogs.prf:
$(HOME)/Qt/6.9.1/macos/mkspecs/features/testcase_targets.prf:
$(HOME)/Qt/6.9.1/macos/mkspecs/features/exceptions.prf:
$(HOME)/Qt/6.9.1/macos/mkspecs/features/yacc.prf:
$(HOME)/Qt/6.9.1/macos/mkspecs/features/lex.prf:
../VSPSetup.pro:
qmake: FORCE
	@$(QMAKE) -o VSPSetup.xcodeproj/project.pbxproj ../VSPSetup.pro -spec macx-xcode

qmake_all: FORCE

